### ISSUE TITLE
CAS Plugin not available any more from the Jenkins Update Center

### ISSUE THREAD

**Issue by ilgrosso** [fcrespel/jenkins-cas-plugin#8]
It does not show up after refreshing.
Also, it seems to be listed any more under http://updates.jenkins-ci.org/download/plugins/

**Comment by fcrespel** [comment]
I was not aware of it, but I guess it was removed due to this security bulletin: https://jenkins.io/security/advisory/2017-04-10/#cas-plugin

I'm not sure what to do to fix it yet, I'll try to find out ASAP. At worse I will disable/remove the offending feature altogether.

**Comment by sdorra** [comment]
The issue is related to the role parsing of the cas 1 protocol. I think the options are:

* remove outdated cas 1 protocol
* remove support for the role parsing groovy script
* execute the role parsing script with the groovy sandbox provided by the [script-security plugin](https://plugins.jenkins.io/script-security)

**Comment by fcrespel** [comment]
I have implemented support for the Script Security plugin (79a9bd1) and added a check for the Run Scripts permission (d8aba2a) in the latest version, currently 1.4.0-SNAPSHOT.

If you can, please test it and let me know if it works for you before I release it.

**Comment by fcrespel** [comment]
Version 1.4.0 is released and back in the Update Center / plugins directory: https://plugins.jenkins.io/cas-plugin
